# Generated by Django 4.1.1 on 2022-09-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensario', '0002_cliente_proveedor_venta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proveedor',
            new_name='proveedores',
        ),
    ]
