# Generated by Django 4.1.1 on 2022-09-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensario', '0003_rename_proveedor_proveedores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proveedores',
            new_name='proveedore',
        ),
    ]
